spring:
  h2:
    console:
      enabled: false
      path: /h2-console
  # 数据源配置
  datasource:
    url: jdbc:h2:file:./db/jdv;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;
    username: jdataview
    password: jdataview
    driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:db/init.sql
      username: jdataview
      password: jdataview
      mode: always
      continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: create-drop

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.sunyaxing.imagine.jdataviewserver.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
#  configuration:
#    # 打印sql
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true
#    cache-enabled: true
#    call-setters-on-nulls: true
#    jdbc-type-for-null: 'null'